// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type IPOAlert struct {
	CompanyName            string `json:"company_name"`
	StockSymbol            string `json:"stock_symbol"`
	ShareRegistrar         string `json:"share_registrar"`
	SectorName             string `json:"sector_name"`
	ShareType              string `json:"share_type"`
	PricePerUnit           string `json:"price_per_unit"`
	Rating                 string `json:"rating"`
	Units                  string `json:"units"`
	MinUnits               string `json:"min_units"`
	MaxUnits               string `json:"max_units"`
	TotalAmount            string `json:"total_amount"`
	OpeningDateAd          string `json:"opening_date_ad"`
	OpeningDateBs          string `json:"opening_date_bs"`
	ClosingDateAd          string `json:"closing_date_ad"`
	ClosingDateBs          string `json:"closing_date_bs"`
	ClosingDateClosingTime string `json:"closing_date_closing_time"`
	Status                 string `json:"status"`
}

type IPOAndFpoAlert struct {
	Ipo []*IPOAlert `json:"ipo"`
	Fpo []*IPOAlert `json:"fpo"`
}

type Indices struct {
	IndexName           string  `json:"index_name"`
	IndexValue          float64 `json:"index_value"`
	PreviousValue       float64 `json:"previous_value"`
	OpeningValue        float64 `json:"opening_value"`
	PercentChange       float64 `json:"percent_change"`
	Difference          float64 `json:"difference"`
	Turnover            float64 `json:"turnover"`
	Volume              int32   `json:"volume"`
	NoOfListedCompanies int32   `json:"no_of_listed_companies"`
	NoOfTradedCompanies int32   `json:"no_of_traded_companies"`
	NoOfTransactions    int32   `json:"no_of_transactions"`
	NoOfListedShares    int32   `json:"no_of_listed_shares"`
	MarketCap           float64 `json:"market_cap"`
	DayHigh             float64 `json:"day_high"`
	DayLow              float64 `json:"day_low"`
	YearHigh            float64 `json:"year_high"`
	YearLow             float64 `json:"year_low"`
	AsOfDate            string  `json:"as_of_date"`
	AsOfDateString      string  `json:"as_of_date_string"`
	NoOfGainers         int32   `json:"no_of_gainers"`
	NoOfLosers          int32   `json:"no_of_losers"`
	NoOfUnchanged       int32   `json:"no_of_unchanged"`
}

type Market struct {
	Symbol           string  `json:"symbol"`
	Company          string  `json:"company"`
	TradeVolume      int32   `json:"tradeVolume"`
	High             float64 `json:"high"`
	Low              float64 `json:"low"`
	Open             float64 `json:"open"`
	Close            float64 `json:"close"`
	TotalTradedValue float64 `json:"totalTradedValue"`
	PrevClose        float64 `json:"prevClose"`
	PriceChange      float64 `json:"priceChange"`
	PercentChange    float64 `json:"percentChange"`
	ShareVolume      int32   `json:"shareVolume"`
	Lastupdated      string  `json:"lastupdated"`
}

type MarketMover struct {
	StockSymbol      string  `json:"stock_symbol"`
	CompanyName      string  `json:"company_name"`
	NoOfTransactions int32   `json:"no_of_transactions"`
	MaxPrice         float64 `json:"max_price"`
	MinPrice         float64 `json:"min_price"`
	OpeningPrice     float64 `json:"opening_price"`
	ClosingPrice     float64 `json:"closing_price"`
	Amount           float64 `json:"amount"`
	PreviousClosing  float64 `json:"previous_closing"`
	DifferenceRs     float64 `json:"difference_rs"`
	PercentChange    float64 `json:"percent_change"`
	Volume           int32   `json:"volume"`
	TradeDate        string  `json:"trade_date"`
}

type MarketMovers struct {
	Gainers []*MarketMover `json:"gainers"`
	Losers  []*MarketMover `json:"losers"`
}

type MarketStatus struct {
	IsMarketOpen bool `json:"isMarketOpen"`
}

type NepseIndex struct {
	IndexName     string  `json:"index_name"`
	IndexValue    float64 `json:"index_value"`
	PreviousValue float64 `json:"previous_value"`
	OpeningValue  float64 `json:"opening_value"`
	PercentChange float64 `json:"percent_change"`
	Difference    float64 `json:"difference"`
	Turnover      float64 `json:"turnover"`
	Volume        int32   `json:"volume"`
	MarketCap     float64 `json:"market_cap"`
	DayHigh       float64 `json:"day_high"`
	DayLow        float64 `json:"day_low"`
	YearHigh      float64 `json:"year_high"`
	YearLow       float64 `json:"year_low"`
	AsOfDate      string  `json:"as_of_date"`
}

type Query struct {
}
